from . import (
    research_agent,
    csv_export_agent,
    content_agent,
    render_agent,
    packaging_agent,
    notion_agent,
    notion_content_agent,
    catalog_agent,
    visual_agent,
    diagram_agent,
    notion_schema_agent,
    gumroad_agent,
    landing_agent,
    social_agent,
    market_agent,
    image_agent,
)

AGENT_REGISTRY = {
    "research_agent": research_agent.run,
    "csv_export_agent": csv_export_agent.run,
    "content_agent": content_agent.run,
    "render_agent": render_agent.run,
    "packaging_agent": packaging_agent.run,
    "notion_agent": notion_agent.run,
    "notion_content_agent": notion_content_agent.run,
    "catalog_agent": catalog_agent.run,
    "visual_agent": visual_agent.run,
    "diagram_agent": diagram_agent.run,
    "notion_schema_agent": notion_schema_agent.run,
    "gumroad_agent": gumroad_agent.run,
    "landing_agent": landing_agent.run,
    "social_agent": social_agent.run,
    "market_agent": market_agent.run,
    "image_agent": image_agent.run,
}
